### ISSUE TITLE
Short evaluation for AND/OR

### ISSUE THREAD

**Issue by Tezar** [jwadhams/json-logic-php#12]
There is inconsistency with the JS implementation at least for `and`/`or` operators. The values are lazily evaluated in JS (while the docs doesn't specificaly mandates it, it hints it in the "sophisticated level" explanation). 
E.g. logic `{"or": [10, {"log":"wont be evaluated"}]}` will correctly return 10 in both of the implementations, but `log` won't be evaluated on JS. 

This is behaviour could be problematic when one expects same client and server side behaviour. My issue rises when using custom operators like `{"or": [{"get_cache":"key"}, {"expensive_db_query":"key"}]}`, it will be nevertheless always evaluated in its whole.

This can be worked around with the `if` chaining, so it is not a showstopper. But it would be nice at least to mention this difference in the docs.

**Comment by jwadhams** [comment]
OMG how did I not notice this, I'm going to schedule some time into next sprint to work on this.

**Comment by jwadhams** [comment]
OK, this is merged up, take a look at version 1.5.0 and let me know if there's anything else I can update for you.
