### ISSUE TITLE
Custom Operations for PHP

### ISSUE THREAD

**Issue by danielwolf1** [jwadhams/json-logic-php#14]
Hi there. Ist there a way to write custom operations for the PHP library as well? As there are custom operations for JS I was wondering if there is a simple solution for PHP.

Thanks.

**Comment by jwadhams** [comment]
Ah dang it, the docs are just out of date. Check out `JsonLogic::add_operation` at https://github.com/jwadhams/json-logic-php/blob/master/src/JWadhams/JsonLogic.php#L426
