### ISSUE TITLE
PHP 7.4 using curly brackets is deprecated

### ISSUE THREAD

**Issue by szabacsik** [jwadhams/json-logic-php#7]
Deprecated: Array and string offset access syntax with curly braces is deprecated in 
...\vendor\jwadhams\json-logic-php\src\JWadhams\JsonLogic.php on line 361

**Comment by Ali1** [comment]
Yes seeing these errors too.

**Comment by jwadhams** [comment]
I'm able to look into this today, sounds like it can probably be rewritten to use `mb_substr` ?

**Comment by Ali1** [comment]
https://wiki.php.net/rfc/deprecate_curly_braces_array_access

I think it is literally the same as just using square brackets

**Comment by jwadhams** [comment]
Ha, that's a super useful rfc, I was also under the misconception that {} and [] were slightly different. Makes a strong case for the deprecation 🙃

**Comment by jwadhams** [comment]
OK, take a look at tag 1.4.1, both the deprecations introduced in PHP 7.4 are resolved for me.
